### ISSUE TITLE
Make X-Github-Event optional for Gitlab usage

### ISSUE THREAD

**Issue by fnogatz** [nlf/node-github-hook#15]
I want to use githubhook for [Gitlab](https://github.com/gitlabhq/gitlabhq) as well. Its [payload](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md) is very similar. Unfortunately there is no `X-Github-Event` header set, so your [script](https://github.com/nlf/node-github-hook/blob/master/index.js#L149) will return a `404`. I have commented out  this section and the rest is working for Gitlab too!
(Although the `event` variable remains undefined as neither Gitlab's payload is sending the event type explicitly nor a header similar to `X-Github-Event`. But that's okay.)

I think the easiest way would be to add a config option to omit the check for the `X-Github-Event` header field? :)

**Comment by nlf** [comment]
looks like gitlab now sends an `X-Gitlab-Event` header, so this support is on its way
