### ISSUE TITLE
Add functionality as middleware (express4) ?

### ISSUE THREAD

**Issue by yyolk** [nlf/node-github-hook#16]
I would like to try my hand at turning the work you did in the handler into a middleware that than can be used to also run health checks or simultaneously respond to REST requests.

I think there is a possibility of making this module function both as a middleware and as it's own server

**Comment by adrienjoly** [comment]
For reference, the following express middleware worked well for me: [express-github-webhook](https://www.npmjs.com/package/express-github-webhook)

Here's what my server looks like:

```js
const express = require('express');
const bodyParser = require('body-parser');
const GithubWebHook = require('express-github-webhook');
const github = GithubWebHook({
  path: '/github/callback', // for compatibility with npm:githubhook
  secret: process.env.GITHUB_WEBHOOK_SECRET
});

// use in your express app 
let app = express();
app.use(bodyParser.json());
app.use(github);

github.on('push', function (event, repo, ref, data) {
  console.log("Received a push from GitHub!");
});

app.get('/', (req, res) => {
  res.send('ok');
});

const listener = app.listen(process.env.PORT, () => {
  console.log('Server up and running 🏃');
});
```
