### ISSUE TITLE
Clear listeners, stop listening

### ISSUE THREAD

**Issue by blargism** [nlf/node-github-hook#17]
I use this plugin to help with a CI interface I'm building.  When my configurations change I need a way to clear out the listeners so I can re-attach them with the update configurations, then I also would like a way to stop the service altogether.

**Comment by nlf** [comment]
clearing event listeners is already possible, seeing as this module simply extends a standard node event emitter. just call `githubhook.removeAllListeners('eventname')` to remove the listeners for a given event.

i'll add a `stop` function to the server though.
