### ISSUE TITLE
Pass repo, ref to CLI client script

### ISSUE THREAD

**Issue by robwilkerson** [nlf/node-github-hook#35]
I'm working in a shared environment where I'd like the CLI client to manage updates for multiple projects on the same box. This would allow me to run a single `githubhook` daemon. It's callback is a bash script that, in turn, be the puppet master for individual projects.

As it stands right now, however, no data is sent to the script from the CLI client so the callback can't do any decisioning based on what was updated. As far as I can tell, forwarding these data points along as arguments shouldn't cause any issues for existing scripts that wouldn't be looking for arguments anyway.

Would you be open to a pull request that would send this information along?

**Comment by robwilkerson** [comment]
If so, I'm finding that the client callback function gets 3 args (repo, ref, data). Is it safe to expect that to always be the case? If not, will the `data` arg _always_ be the last arg? I can extract repo and ref from the data arg if I know how/where to find it.

**Comment by nlf** [comment]
repo and ref are easy enough, the full data blob we'd probably have to stringify and send as one big argument though. should work fine, people will just have to be aware of the need to parse that third argument
