### ISSUE TITLE
How to run command line utility continuously?

### ISSUE THREAD

**Issue by eablokker** [nlf/node-github-hook#36]
I tried running in background but it quits after first run.

I tried running with the forever command line tool, but forever becomes unresponsive.

**Comment by nlf** [comment]
it shouldn't be quitting.. do you get an error? or does it just stop silently?

**Comment by eablokker** [comment]
Stops silenty. Maybe I don't understand how to run a process in the background after logout. I run `githubhook`, then hit `Ctrl + Z`, then run `bg`. I tried using the `disown -h %1` command too. Using `ps x` to see running processes. It does seem to continue running after logging out and back in. I'm not sure when exactly it's quitting, but when I come back the next day it's stopped.

**Comment by nlf** [comment]
this sounds like either an issue with your script or something that needs to be taken care of by your operating system's init system. either way, this is a very old issue so i'm going to close it.
